config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :groups, only: [:index, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :comments, only: [:index, :show, :destroy]
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  get "users" => redirect("/users/sign_up")

  root to: "public/homes#top"

  namespace :public do
    get 'about', to: 'homes#about'

    get "posts/search", to: "posts#search", as: "search_public_posts"

    resources :users, only: [:index, :show, :edit, :update] do
      collection do
        get 'mypage'
        get 'confirm_withdraw'
        delete 'withdraw'
      end
    end

    resources :user_groups, only: [] do
      member do
        patch :accept
        delete :reject
      end
    end

    resources :groups do
      collection do
        get 'invite'  
        get 'select_group', to: 'groups#select_group'
      end

      member do
        post 'accept_invitation'
        delete 'reject_invitation'
        get 'invite_existing'  
        post 'send_invites'   
        get 'calendar'
        get 'confirm_withdraw'
        delete 'withdraw'
        post 'send_invite', to: 'groups#send_invite'
      end

      resources :posts do
        resources :comments, only: [:index, :new, :create, :edit, :update, :destroy]
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  def index
    @comments = Comment
                  .includes(:user, :post)
                  .order(created_at: :desc)
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_comments_path, notice: "コメントを削除しました。"
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<h1>コメント一覧</h1>

<table>
  <thead>
    <tr>
      <th>コメント内容</th>
      <th>投稿</th>
      <th>ユーザー</th>
      <th>投稿日</th>
      <th>操作</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td>
          <%= link_to truncate(comment.body, length: 40), admin_comment_path(comment) %>
        </td>

        <td>
          <%= link_to comment.post.title, admin_post_path(comment.post) %>
        </td>

        <td>
          <%= link_to "#{comment.user.last_name} #{comment.user.first_name}",
                      admin_user_path(comment.user) %>
        </td>

        <td>
          <%= l comment.created_at, format: :short %>
        </td>

        <td>
          <%= link_to "削除",
                      admin_comment_path(comment),
                      method: :delete,
                      data: { confirm: "このコメントを削除しますか？" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/comments/show.html.erb
<h1>コメント詳細</h1>

<p>
  <strong>ID：</strong>
  <%= @comment.id %>
</p>

<p>
  <strong>コメント内容：</strong><br>
  <%= simple_format(@comment.body) %>
</p>

<p>
  <strong>投稿：</strong>
  <%= link_to @comment.post.title,
              admin_post_path(@comment.post) %>
</p>

<p>
  <strong>ユーザー：</strong>
  <%= link_to "#{@comment.user.last_name} #{@comment.user.first_name}",
              admin_user_path(@comment.user) %>
</p>

<p>
  <strong>作成日時：</strong>
  <%= l @comment.created_at, format: :long %>
</p>

<hr>

<%= link_to "コメント一覧に戻る", admin_comments_path %> |
<%= link_to "削除",
            admin_comment_path(@comment),
            method: :delete,
            data: { confirm: "本当に削除しますか？" } %>