config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :groups, only: [:index, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :comments, only: [:index, :show, :destroy]
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  get "users" => redirect("/users/sign_up")

  root to: "public/homes#top"

  namespace :public do
    get 'about', to: 'homes#about'

    get "posts/search", to: "posts#search", as: "search_public_posts"

    resources :users, only: [:index, :show, :edit, :update] do
      collection do
        get 'mypage'
        get 'confirm_withdraw'
        delete 'withdraw'
      end
    end

    resources :user_groups, only: [] do
      member do
        patch :accept
        delete :reject
      end
    end

    resources :groups do
      collection do
        get 'invite'  
        get 'select_group', to: 'groups#select_group'
      end

      member do
        post 'accept_invitation'
        delete 'reject_invitation'
        get 'invite_existing'  
        post 'send_invites'   
        get 'calendar'
        get 'confirm_withdraw'
        delete 'withdraw'
        post 'send_invite', to: 'groups#send_invite'
      end

      resources :posts do
        resources :comments, only: [:index, :new, :create, :edit, :update, :destroy]
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :group

  validates :title, presence: true
  validates :body, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validate :end_after_start

  private

  def end_after_start
    return if start_at.blank? || end_at.blank?
    if end_at < start_at
      errors.add(:end_at, "は開始日時より後でなければなりません")
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  def index
    @posts = Post
               .includes(:user, :group)
               .order(created_at: :desc)

    if params[:keyword].present?
     @posts = @posts.where(
      "title LIKE ? OR body LIKE ?",
      "%#{params[:keyword]}%",
      "%#{params[:keyword]}%"
     )
    end
                         
  end
  

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_post_path(@post), notice: "投稿を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: "投稿を削除しました。"
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :start_at, :end_at)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/edit.html.erb
<h1>投稿編集</h1>

<%= form_with model: @post, url: admin_post_path(@post), method: :patch, local: true do |f| %>
  <div>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </div>

  <br>

  <div>
    <%= f.label :body, "本文" %><br>
    <%= f.text_area :body, rows: 8 %>
  </div>

  <br>

  <div>
    <%= f.label :start_at, "開始日時" %><br>
    <%= f.datetime_select :start_at %>
  </div>

  <br>

  <div>
    <%= f.label :end_at, "終了日時" %><br>
    <%= f.datetime_select :end_at %>
  </div>

  <br>

  <%= f.submit "更新する" %>
<% end %>

<hr>

<%= link_to "投稿を削除する",
            admin_post_path(@post),
            method: :delete,
            data: { confirm: "この投稿を削除しますか？" } %>

<br><br>

<%= link_to "詳細ページに戻る", admin_post_path %>

app/views/admin/posts/index.html.erb
<h1>投稿一覧</h1>

<!-- 検索フォーム -->
<div style="margin-bottom: 20px;">
  <%= form_with url: admin_posts_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, value: params[:keyword], placeholder: "タイトル・本文で検索" %>
    <%= f.submit "検索" %>
  <% end %>
</div>

<!-- 投稿一覧 -->
<table border="1" cellpadding="8" cellspacing="0">
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>投稿者</th>
      <th>グループ</th>
      <th>投稿日時</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td>
          <%= link_to post.title, admin_post_path(post) %>
        </td>
        <td>
          <%= post.user.last_name %> <%= post.user.first_name %>
        </td>
        <td>
          <%= post.group.name %>
        </td>
        <td>
          <%= post.created_at.strftime("%Y/%m/%d %H:%M") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/posts/show.html.erb
<h1>投稿詳細</h1>

<table border="1" cellpadding="8" cellspacing="0">
  <tr>
    <th>ID</th>
    <td><%= @post.id %></td>
  </tr>

  <tr>
    <th>タイトル</th>
    <td><%= @post.title %></td>
  </tr>

  <tr>
    <th>本文</th>
    <td><%= simple_format(@post.body) %></td>
  </tr>

  <tr>
    <th>投稿者</th>
    <td>
      <%= @post.user.last_name %> <%= @post.user.first_name %>
    </td>
  </tr>

  <tr>
    <th>グループ</th>
    <td>
      <%= link_to @post.group.name, admin_group_path(@post.group) %>
    </td>
  </tr>

  <tr>
    <th>投稿日</th>
    <td><%= @post.created_at.strftime("%Y/%m/%d %H:%M") %></td>
  </tr>

  <tr>
    <th>最終更新</th>
    <td><%= @post.updated_at.strftime("%Y/%m/%d %H:%M") %></td>
  </tr>
</table>

<br>

<%= link_to "編集する", edit_admin_post_path(@post) %> |
<%= link_to "投稿一覧に戻る", admin_posts_path %>