config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :groups, only: [:index, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :comments, only: [:index, :show, :destroy]
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  get "users" => redirect("/users/sign_up")

  root to: "public/homes#top"

  namespace :public do
    get 'about', to: 'homes#about'

    get "posts/search", to: "posts#search", as: "search_public_posts"

    resources :users, only: [:index, :show, :edit, :update] do
      collection do
        get 'mypage'
        get 'confirm_withdraw'
        delete 'withdraw'
      end
    end

    resources :user_groups, only: [] do
      member do
        patch :accept
        delete :reject
      end
    end

    resources :groups do
      collection do
        get 'invite'  
        get 'select_group', to: 'groups#select_group'
      end

      member do
        post 'accept_invitation'
        delete 'reject_invitation'
        get 'invite_existing'  
        post 'send_invites'   
        get 'calendar'
        get 'confirm_withdraw'
        delete 'withdraw'
        post 'send_invite', to: 'groups#send_invite'
      end

      resources :posts do
        resources :comments, only: [:index, :new, :create, :edit, :update, :destroy]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  
  scope :active, -> { where(is_active: true) }

  has_many :user_groups, dependent: :destroy
  has_many :groups, -> { where(user_groups: { status: :accepted }) }, through: :user_groups
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :owned_groups, class_name: "Group", foreign_key: "owner_id", dependent: :nullify

  def accepted_groups
    groups
  end

  def active_for_authentication?
    super && is_active?
  end
  
  def inactive_message
    is_active? ? super : :inactive_account
  end

  def full_name
    "#{last_name} #{first_name}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @keyword = params[:keyword]
  
    @users = User
               .includes(:groups, :posts)
               .order(created_at: :desc)
  
    if @keyword.present?
      @users = @users.where(
        "last_name LIKE ? OR first_name LIKE ? OR email LIKE ?",
        "%#{@keyword}%",
        "%#{@keyword}%",
        "%#{@keyword}%"
      )
    end
  end  

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.update(is_active: false)
    redirect_to admin_users_path, notice: "ユーザーを退会状態にしました。"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :is_active)
  end  

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>ユーザー編集</h1>

<%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>

  <h2>基本情報</h2>

  <div>
    <%= f.label :last_name, "姓" %><br>
    <%= f.text_field :last_name %>
  </div>

  <div>
    <%= f.label :first_name, "名" %><br>
    <%= f.text_field :first_name %>
  </div>

  <div>
    <%= f.label :email, "メールアドレス" %><br>
    <%= f.email_field :email %>
  </div>

  <hr>

  <h2>ステータス</h2>

  <div>
    <%= f.label :is_active, "アカウント状態" %><br>
    <%= f.select :is_active, [["有効", true], ["退会", false]] %>
  </div>

  <hr>

  <%= f.submit "更新する" %>
<% end %>

<br>

<%= link_to "ユーザー詳細に戻る", admin_user_path(@user) %> |
<%= link_to "ユーザー一覧に戻る", admin_users_path %>

app/views/admin/users/index.html.erb
<h1>ユーザー一覧</h1>

<%= form_with url: admin_users_path, method: :get, local: true do |f| %>
  <%= f.text_field :keyword, value: params[:keyword], placeholder: "名前・メールで検索" %>
  <%= f.submit "検索" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>メール</th>
      <th>ステータス</th>
      <th>グループ数</th>
      <th>投稿数</th>
      <th>登録日</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to "#{user.last_name} #{user.first_name}", admin_user_path(user) %>
        </td>
        <td><%= user.email %></td>
        <td>
          <%= user.is_active ? "有効" : "退会" %>
        </td>
        <td><%= user.groups.size %></td>
        <td><%= user.posts.size %></td>
        <td><%= l user.created_at, format: :short %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/show.html.erb
<h1>ユーザー詳細</h1>

<h2>基本情報</h2>
<p><strong>名前：</strong><%= @user.last_name %> <%= @user.first_name %></p>
<p><strong>メール：</strong><%= @user.email %></p>
<p><strong>ステータス：</strong><%= @user.is_active ? "有効" : "退会" %></p>
<p><strong>登録日：</strong><%= l @user.created_at, format: :short %></p>

<hr>

<h2>利用状況</h2>
<ul>
  <li>所属グループ数：<%= @user.groups.count %></li>
  <li>投稿数：<%= @user.posts.count %></li>
  <li>コメント数：<%= @user.comments.count %></li>
</ul>

<hr>

<h2>所属グループ</h2>
<ul>
  <% @user.groups.each do |group| %>
    <li>
      <%= link_to group.name, admin_group_path(group) %>
    </li>
  <% end %>
</ul>

<hr>

<h2>投稿一覧</h2>
<ul>
  <% @user.posts.each do |post| %>
    <li>
      <%= link_to post.title, admin_post_path(post) %>
    </li>
  <% end %>
</ul>

<hr>

<%= link_to "ユーザー一覧に戻る", admin_users_path %> |
<%= link_to "編集", edit_admin_user_path(@user) %>