config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :groups, only: [:index, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :comments, only: [:index, :show, :destroy]
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  get "users" => redirect("/users/sign_up")

  root to: "public/homes#top"

  namespace :public do
    get 'about', to: 'homes#about'

    get "posts/search", to: "posts#search", as: "search_public_posts"

    resources :users, only: [:index, :show, :edit, :update] do
      collection do
        get 'mypage'
        get 'confirm_withdraw'
        delete 'withdraw'
      end
    end

    resources :user_groups, only: [] do
      member do
        patch :accept
        delete :reject
      end
    end

    resources :groups do
      collection do
        get 'invite'  
        get 'select_group', to: 'groups#select_group'
      end

      member do
        post 'accept_invitation'
        delete 'reject_invitation'
        get 'invite_existing'  
        post 'send_invites'   
        get 'calendar'
        get 'confirm_withdraw'
        delete 'withdraw'
        post 'send_invite', to: 'groups#send_invite'
      end

      resources :posts do
        resources :comments, only: [:index, :new, :create, :edit, :update, :destroy]
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
            
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :accepted_users, -> { where(user_groups: { status: :accepted }) }, through: :user_groups, source: :user
  has_many :posts, dependent: :destroy
  
  belongs_to :owner, class_name: "User"
  
  validates :name, presence: true
  validates :explanation, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :group

  validates :title, presence: true
  validates :body, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validate :end_after_start

  private

  def end_after_start
    return if start_at.blank? || end_at.blank?
    if end_at < start_at
      errors.add(:end_at, "は開始日時より後でなければなりません")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  
  scope :active, -> { where(is_active: true) }

  has_many :user_groups, dependent: :destroy
  has_many :groups, -> { where(user_groups: { status: :accepted }) }, through: :user_groups
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :owned_groups, class_name: "Group", foreign_key: "owner_id", dependent: :nullify

  def accepted_groups
    groups
  end

  def active_for_authentication?
    super && is_active?
  end
  
  def inactive_message
    is_active? ? super : :inactive_account
  end

  def full_name
    "#{last_name} #{first_name}"
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group

  enum status: { pending: 0, accepted: 1, declined: 2 }

  validates :user_id, uniqueness: { scope: :group_id }
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @keyword = params[:keyword]
  
    @groups =
      if @keyword.present?
        Group
          .where("name LIKE ?", "%#{@keyword}%")
          .includes(:owner, :users, :posts)
          .order(created_at: :desc)
      else
        Group
          .includes(:owner, :users, :posts)
          .order(created_at: :desc)
      end
  end  
  
  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to admin_group_path(@group), notice: "グループを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to admin_groups_path, notice: "グループを削除しました。"
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end  

  def group_params
    params.require(:group).permit(:name, :explanation)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::ApplicationController
  skip_before_action :authenticate_admin!, only: [:top]
  
  def top
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  def index
    @posts = Post
               .includes(:user, :group)
               .order(created_at: :desc)

    if params[:keyword].present?
     @posts = @posts.where(
      "title LIKE ? OR body LIKE ?",
      "%#{params[:keyword]}%",
      "%#{params[:keyword]}%"
     )
    end
                         
  end
  

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_post_path(@post), notice: "投稿を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: "投稿を削除しました。"
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :start_at, :end_at)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @keyword = params[:keyword]
  
    @users = User
               .includes(:groups, :posts)
               .order(created_at: :desc)
  
    if @keyword.present?
      @users = @users.where(
        "last_name LIKE ? OR first_name LIKE ? OR email LIKE ?",
        "%#{@keyword}%",
        "%#{@keyword}%",
        "%#{@keyword}%"
      )
    end
  end  

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.update(is_active: false)
    redirect_to admin_users_path, notice: "ユーザーを退会状態にしました。"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :is_active)
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_authentication
  
  private

  def configure_authentication
    if admin_controller?
      authenticate_admin!
    else
      authenticate_user! unless action_is_public?
    end
  end
 
  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end

  def action_is_public?
    controller_name == 'homes' && %w[top about].include?(action_name)
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <% if admin_signed_in? %>
        <nav>
          <%= link_to 'Home（グループ一覧）', admin_groups_path %> |
          <%= link_to 'ユーザー一覧', admin_users_path %> |
          <%= link_to '投稿一覧', admin_posts_path %> |
          <%= link_to 'コメント一覧', admin_comments_path %> |
          <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
        </nav>
      <% end %>
    </header>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareWith</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://kit.fontawesome.com/4d881a0b97.js" crossorigin="anonymous"></script>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <header>
    <% if controller_name == 'homes' && action_name == 'top' %>
      <h1>share_with（トップページ）</h1>
    <% end %>

    <nav>
      <ul>
        <% if user_signed_in? %>
          <!-- ログイン後のメニュー -->
          <li><%= link_to "Home(グループ一覧)", public_groups_path %></li>
          <li><%= link_to "マイページ", mypage_public_users_path %></li>
          <li><%= link_to "ユーザー検索", public_users_path %></li>
          <li><%= link_to "投稿検索", public_search_public_posts_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <!-- ログイン前のメニュー -->
          <% unless controller_name == 'homes' && action_name == 'about' %>
            <% unless controller_name == 'sessions' && action_name == 'new' %>
              <li><%= link_to "ログイン", new_user_session_path %></li>
            <% end %>
            <% unless controller_name == 'registrations' %>
              <li><%= link_to "新規登録", new_user_registration_path %></li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </nav>
  </header>

  <% flash.each do |key, message| %>
    <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %>">
      <%= message %>
    </div>
  <% end %>

  <%= yield %>

  <footer>
    <% if !user_signed_in? && !(controller_name == 'homes' && action_name == 'about') %>
      <!-- ログイン前かつaboutページ以外ではAboutリンクを表示 -->
      <%= link_to "share_withとは？", public_about_path %>
    <% elsif controller_name == 'homes' && action_name == 'about' %>
      <!-- Aboutページではログイン・新規登録リンクを本文に含める -->
      <p>今すぐ始めたい方はこちら：</p>
      <ul>
        <li><%= link_to "新規登録はこちら", new_user_registration_path %></li>
        <li><%= link_to "ログインはこちら", new_user_session_path %></li>
      </ul>
    <% end %>
  </footer>
</body>
</html>